function sys = deepc2_systems(sys_type)
    switch sys_type
        case 'example0'
            sys = struct( ...
                'A', [1 -0.01 0; ...
                      0.01 1 0;
                      0 0 0.8], ...  
                'B', eye(3,2), ...
                'C', eye(3), ...
                'D', zeros(3, 2) ...
             );
    end
end

